# HR Analytics Project - Employee Attrition Analysis

## Business Problem

- Employee attrition is a major challenge for organizations as it increases recruitment costs, affects productivity, and results in the loss of experienced employees.
- The objective of this project is to analyze HR data to identify the key factors associated with employee attrition.
- By exploring employee demographics, job roles, departments, salary, and other HR attributes, the organization can gain insights to improve employee retention and support data-driven workforce decisions.

## Importing libraries

In [63]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

## Load the Dataset

In [64]:
df = pd.read_csv("HR_Analytics.csv")

## 1. Data Understanding

- This section helps in understanding the dataset by examining its structure, shape, data types, and statistical summary

In [10]:
df.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,3,80,0,0,2,3,0,0,0,0.0
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,4,80,0,0,3,3,0,0,0,0.0
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0.0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1473 entries, 0 to 1479
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmpID                     1473 non-null   object
 1   Age                       1473 non-null   int64
 2   AgeGroup                  1473 non-null   object
 3   Attrition                 1473 non-null   object
 4   BusinessTravel            1473 non-null   object
 5   DailyRate                 1473 non-null   int64
 6   Department                1473 non-null   object
 7   DistanceFromHome          1473 non-null   int64
 8   Education                 1473 non-null   int64
 9   EducationField            1473 non-null   object
 10  EmployeeCount             1473 non-null   int64
 11  EmployeeNumber            1473 non-null   int64
 12  EnvironmentSatisfaction   1473 non-null   int64
 13  Gender                    1473 non-null   object
 14  HourlyRate                1473 non-null   int64
 15  JobInvolvement            1473 non-null   int64
 16  JobLevel                  1473 non-null   int64
 17  JobRole                   1473 non-null   object
 18  JobSatisfaction           1473 non-null   int64
 19  MaritalStatus             1473 non-null   object
 20  MonthlyIncome             1473 non-null   int64
 21  SalarySlab                1473 non-null   object
 22  MonthlyRate               1473 non-null   int64
 23  NumCompaniesWorked        1473 non-null   int64
 24  Over18                    1473 non-null   object
 25  OverTime                  1473 non-null   object
 26  PercentSalaryHike         1473 non-null   int64
 27  PerformanceRating         1473 non-null   int64
 28  RelationshipSatisfaction  1473 non-null   int64
 29  StandardHours             1473 non-null   int64
 30  StockOptionLevel          1473 non-null   int64
 31  TotalWorkingYears         1473 non-null   int64
 32  TrainingTimesLastYear     1473 non-null   int64
 33  WorkLifeBalance           1473 non-null   int64
 34  YearsAtCompany            1473 non-null   int64
 35  YearsInCurrentRole        1473 non-null   int64
 36  YearsSinceLastPromotion   1473 non-null   int64
 37  YearsWithCurrManager      1473 non-null   float64
dtypes: float64(1), int64(25), object(12)
memory usage: 448.8+ KB

In [36]:
df.shape

(1473, 38)

In [17]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1480.000000,1480.000000,1480.000000,1480.000000,1480.0,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,...,1480.000000,1480.0,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1423.000000
mean,36.917568,801.384459,9.220270,2.910811,1.0,1031.860811,2.724324,65.845270,2.729730,2.064865,...,2.708784,80.0,0.791892,11.281757,2.797973,2.760811,7.009459,4.228378,2.182432,4.118060
std,9.128559,403.126988,8.131201,1.023796,0.0,605.955046,1.092579,20.328266,0.713007,1.105574,...,1.081995,0.0,0.850527,7.770870,1.288791,0.707024,6.117945,3.616020,3.219357,3.555484
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,493.750000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,800.000000,7.000000,3.000000,1.0,1027.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1568.250000,4.000000,83.000000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

**Observation:**

The dataset was successfully loaded and examined.
It contains both numerical and categorical columns.
The data structure and statistical summary provide a clear understanding of the dataset.
The dataset is now ready for further data cleaning and preprocessing.



### 2. Data Cleaning

In [39]:
#check missing values

In [65]:
df.isnull().sum()

EmpID                        0
Age                          0
AgeGroup                     0
Attrition                    0
BusinessTravel               0
DailyRate                    0
Department                   0
DistanceFromHome             0
Education                    0
EducationField               0
EmployeeCount                0
EmployeeNumber               0
EnvironmentSatisfaction      0
Gender                       0
HourlyRate                   0
JobInvolvement               0
JobLevel                     0
JobRole                      0
JobSatisfaction              0
MaritalStatus                0
MonthlyIncome                0
SalarySlab                   0
MonthlyRate                  0
NumCompaniesWorked           0
Over18                       0
OverTime                     0
PercentSalaryHike            0
PerformanceRating            0
RelationshipSatisfaction     0
StandardHours                0
StockOptionLevel             0
TotalWorkingYears            0
TrainingTimesLastYear        0
WorkLifeBalance              0
YearsAtCompany               0
YearsInCurrentRole           0
YearsSinceLastPromotion      0
YearsWithCurrManager        57
dtype: int64

In [ ]:
#fill missing values

In [66]:
df["YearsWithCurrManager"] =df["YearsWithCurrManager"].fillna(df["YearsWithCurrManager"].median())

In [41]:
#verify missing values

In [67]:
df.isnull().sum()

EmpID                       0
Age                         0
AgeGroup                    0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
SalarySlab                  0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

**Observation:**
- The "YearsWithCurrManager" column contained 57 missing values.
- Missing values were replaced with the median to preserve the dataset without significantly affecting the analysis.

In [ ]:
#check duplicate rows

In [68]:
df.duplicated().sum()

np.int64(7)

In [43]:
#remove duplicate rows

In [69]:
df = df.drop_duplicates()

In [45]:
#verify duplicate rows

In [25]:
df.duplicated().sum()

np.int64(0)

**Observation:**
Duplicate records were identified and removed to ensure data quality

### Check Unique Values

In [27]:
df["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [28]:
df["Attrition"].unique()

array(['Yes', 'No'], dtype=object)

In [29]:
df["Department"].unique()

array(['Research & Development', 'Sales', 'Human Resources'], dtype=object)

In [31]:
df["JobRole"].unique()

array(['Laboratory Technician', 'Sales Representative',
       'Research Scientist', 'Human Resources', 'Manufacturing Director',
       'Sales Executive', 'Healthcare Representative',
       'Research Director', 'Manager'], dtype=object)

In [32]:
df["BusinessTravel"].unique()

array(['Travel_Rarely', 'Travel_Frequently', 'Non-Travel', 'TravelRarely'],
      dtype=object)

### Standarize Inconsistent Values

In [70]:
df["BusinessTravel"] = df["BusinessTravel"].replace({"TravelRarely": "Travel_Rarely"})

### Verify The Change

In [71]:
df["BusinessTravel"].unique()

array(['Travel_Rarely', 'Travel_Frequently', 'Non-Travel'], dtype=object)

**Observation:**
- The 'BusinessTravel' column contained inconsistent values ('TravelRarely` and 'Travel_Rarely').
- These values were standardized to 'Travel_Rarely' to ensure consistency.
- After verification, only consistent values remain in the column.

In [46]:
df["EducationField"].unique()

array(['Life Sciences', 'Medical', 'Marketing', 'Technical Degree',
       'Other', 'Human Resources'], dtype=object)

In [47]:
df["MaritalStatus"].unique()

array(['Single', 'Divorced', 'Married'], dtype=object)

In [48]:
df["OverTime"].unique()

array(['No', 'Yes'], dtype=object)

***Overall Observations:***

- Unique values were checked for all important categorical columns.
- An inconsistency was found in the "BusinessTravel" column (`TravelRarely` and `Travel_Rarely`) and was standardized.
- All other categorical columns contained consistent values.
- The dataset is now consistent and ready for exploratory data analysis (EDA).

### Final Verification

In [72]:
print(df.shape)
print(df.isnull().sum())
print(df.duplicated().sum())

(1473, 38)
EmpID                       0
Age                         0
AgeGroup                    0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
SalarySlab                  0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64
0

### Saved Cleaned Dataset

In [73]:
df.to_csv("HR_Analytics_Cleaned.csv", index=False)
print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

### Verfifying Cleaned Dataset

In [74]:
df_check = pd.read_csv("HR_Analytics_Cleaned.csv")

print(df_check.shape)
print(df_check.isnull().sum())

(1473, 38)
EmpID                       0
Age                         0
AgeGroup                    0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
SalarySlab                  0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64